shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
  - jose@4.15.9
  - semver@6.3.1

packages:
  - .

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
